-- ============================================================
-- Elite BBS Rims — Seed File (Scraped from carsaccessoriesstore.store)
-- ============================================================

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ------------------------------------------------------------
-- PRODUCTS (11 items)
-- ------------------------------------------------------------


CREATE TABLE IF NOT EXISTS products (
    id                INT           PRIMARY KEY AUTO_INCREMENT,
    name              VARCHAR(255)  NOT NULL,
    slug              VARCHAR(255)  UNIQUE NOT NULL,
    description       TEXT,
    short_description VARCHAR(500),
    price             DECIMAL(10,2) NOT NULL,
    sale_price        DECIMAL(10,2) DEFAULT NULL,
    sku               VARCHAR(100)  UNIQUE,
    stock             INT           DEFAULT 10,
    category          VARCHAR(100),
    brand             VARCHAR(100),
    size              VARCHAR(50),
    finish            VARCHAR(50),
    fitment_data      TEXT,
    tags              VARCHAR(255)  DEFAULT NULL,
    images            JSON,
    featured          BOOLEAN       DEFAULT FALSE,
    status            ENUM('active','draft') DEFAULT 'active',
    created_at        TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_status   (status),
    INDEX idx_category (category),
    INDEX idx_slug     (slug)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT IGNORE INTO products
    (name, slug, short_description, description, price, sale_price, sku, stock, category, brand, size, finish, images, featured, status)
VALUES
  ('OEM 2022 Shelby GT 500', 'oem-2022-shelby-gt-500', 'Premium Ford wheels, 20 inch, for everyday driving and performance. ', 'upgrade your vehicle with these high-quality ford OEM 2022 Shelby GT 500. Engineered for strength and style, these wheels deliver exceptional performance and a sleek look that transforms your ride. Sold as a complete set of 4 wheels - everything you need for a full installation. Size: 20 inches. Perfect for customers wanting to enhance their vehicle\'s appearance and handling. Compatible with most vehicles using standard bolt patterns. Direct fitment - no modifications required for most applications. Includes manufacturer warranty for peace of mind. Free shipping on orders over $499. Questions? Our expert team is here to help you choose the right wheels.', 1350.00,1350.00, 'OEM2022SHELBYGT500', 10, 'Wheels', 'Ford', '20', '', '["/img/assets/wheel_9993_1.jpg", "/img/assets/wheel_9993_2.jpg"]', false, 'active'),
  ('BMW 20″ RIMS + TIRES', 'bmw-20-rims-tires-2', 'Premium BMW wheels, 20 inch, for everyday driving and performance. ', 'upgrade your vehicle with these high-quality bmw BMW 20&#8243; RIMS + TIRES. Engineered for strength and style, these wheels deliver exceptional performance and a sleek look that transforms your ride. Sold as a complete set of 4 wheels - everything you need for a full installation. Size: 20 inches. Perfect for customers wanting to enhance their vehicle\'s appearance and handling. Compatible with most vehicles using standard bolt patterns. Direct fitment - no modifications required for most applications. Includes manufacturer warranty for peace of mind. Free shipping on orders over $499. Questions? Our expert team is here to help you choose the right wheels.', 1800.00,1800.00, 'BMW20RIMSTIRES2', 10, 'Wheels', 'BMW', '20', '', '["/img/assets/wheel_9982_1.jpg"]', false, 'active'),
  ('4 BMW RIMS + TIRES', '4-bmw-rims-tires', 'Premium BMW wheels, for everyday driving and performance. ', 'upgrade your vehicle with these high-quality bmw 4 BMW RIMS + TIRES. Engineered for strength and style, these wheels deliver exceptional performance and a sleek look that transforms your ride. Sold as a complete set of 4 wheels - everything you need for a full installation. Perfect for customers wanting to enhance their vehicle\'s appearance and handling. Compatible with most vehicles using standard bolt patterns. Direct fitment - no modifications required for most applications. Includes manufacturer warranty for peace of mind. Free shipping on orders over $499. Questions? Our expert team is here to help you choose the right wheels.', 1000.00,1000.00, '4BMWRIMSTIRES', 10, 'Wheels', 'BMW', '', '', '["/img/assets/wheel_9976_1.jpg"]', false, 'active'),
  ('Toyota 4Runner & Hilux JDM 18″ Rally Turbo Fan Style Wheels Rims', 'toyota-4runner-hilux-jdm-18-rally-turbo-fan-style-wheels-rims', 'Premium Toyota wheels, 18 inch, for everyday driving and performance. ', 'upgrade your vehicle with these high-quality toyota Toyota 4Runner &#038; Hilux JDM 18&#8243; Rally Turbo Fan Style Wheels Rims. Engineered for strength and style, these wheels deliver exceptional performance and a sleek look that transforms your ride. Sold as a complete set of 4 wheels - everything you need for a full installation. Size: 18 inches. Perfect for customers wanting to enhance their vehicle\'s appearance and handling. Compatible with most vehicles using standard bolt patterns. Direct fitment - no modifications required for most applications. Includes manufacturer warranty for peace of mind. Free shipping on orders over $499. Questions? Our expert team is here to help you choose the right wheels.', 1500.00,1500.00, 'TOYOTA4RUNNERHILUXJD', 10, 'Wheels', 'Toyota', '18', '', '["/img/assets/wheel_9975_1.jpg"]', false, 'active'),
  ('Rays Gramlights 57dr Sputter Blue', 'rays-gramlights-57dr-sputter-blue', 'Premium Rays Engineering wheels, Blue, for everyday driving and performance. ', 'upgrade your vehicle with these high-quality rays engineering Rays Gramlights 57dr Sputter Blue. Engineered for strength and style, these wheels deliver exceptional performance and a sleek look that transforms your ride. Sold as a complete set of 4 wheels - everything you need for a full installation. Finish: Blue. Perfect for customers wanting to enhance their vehicle\'s appearance and handling. Compatible with most vehicles using standard bolt patterns. Direct fitment - no modifications required for most applications. Includes manufacturer warranty for peace of mind. Free shipping on orders over $499. Questions? Our expert team is here to help you choose the right wheels.', 1200.00,1200.00, 'RAYSGRAMLIGHTS57DRSP', 10, 'Wheels', 'Rays Engineering', '', 'Blue', '["/img/assets/wheel_9974_1.jpg", "/img/assets/wheel_9974_2.jpg"]', false, 'active'),
  ('2022 Toyota Avalon Camry CHR OEM 18″ Dark Grey Black Wheels Rims', '2022-toyota-avalon-camry-chr-oem-18-dark-grey-black-wheels-rims', 'Premium Toyota wheels, 18 inch, Black, for everyday driving and performance. ', 'upgrade your vehicle with these high-quality toyota 2022 Toyota Avalon Camry CHR OEM 18&#8243; Dark Grey Black Wheels Rims. Engineered for strength and style, these wheels deliver exceptional performance and a sleek look that transforms your ride. Sold as a complete set of 4 wheels - everything you need for a full installation. Size: 18 inches. Finish: Black. Perfect for customers wanting to enhance their vehicle\'s appearance and handling. Compatible with most vehicles using standard bolt patterns. Direct fitment - no modifications required for most applications. Includes manufacturer warranty for peace of mind. Free shipping on orders over $499. Questions? Our expert team is here to help you choose the right wheels.', 850.00,850.00, '2022TOYOTAAVALONCAMR', 10, 'Wheels', 'Toyota', '18', 'Black', '["/img/assets/wheel_9973_1.jpg"]', false, 'active'),
  ('26s Forged with tires', '26s-forged-with-tires', 'Premium Forged wheels, for everyday driving and performance. ', 'upgrade your vehicle with these high-quality forged 26s Forged with tires. Engineered for strength and style, these wheels deliver exceptional performance and a sleek look that transforms your ride. Sold as a complete set of 4 wheels - everything you need for a full installation. Perfect for customers wanting to enhance their vehicle\'s appearance and handling. Compatible with most vehicles using standard bolt patterns. Direct fitment - no modifications required for most applications. Includes manufacturer warranty for peace of mind. Free shipping on orders over $499. Questions? Our expert team is here to help you choose the right wheels.', 3500.00,3500.00, '26SFORGEDWITHTIRES', 10, 'Wheels', 'Forged', '', '', '["/img/assets/wheel_9962_1.jpg", "/img/assets/wheel_9962_2.jpg", "/img/assets/wheel_9962_3.jpg"]', false, 'active'),
  ('TE37SL Black Edition III', 'te37sl-black-edition-iii', 'Premium Volk Racing wheels, Black, for everyday driving and performance. ', 'upgrade your vehicle with these high-quality volk racing TE37SL Black Edition III. Engineered for strength and style, these wheels deliver exceptional performance and a sleek look that transforms your ride. Sold as a complete set of 4 wheels - everything you need for a full installation. Finish: Black. Perfect for customers wanting to enhance their vehicle\'s appearance and handling. Compatible with most vehicles using standard bolt patterns. Direct fitment - no modifications required for most applications. Includes manufacturer warranty for peace of mind. Free shipping on orders over $499. Questions? Our expert team is here to help you choose the right wheels.', 1500.00,1500.00, 'TE37SLBLACKEDITIONII', 10, 'Wheels', 'Volk Racing', '', 'Black', '["/img/assets/wheel_9961_1.jpg", "/img/assets/wheel_9961_2.jpg"]', false, 'active'),
  ('Set Of OEM 2022 Shelby GT 500 Wheels', 'set-of-oem-2022-shelby-gt-500-wheels', 'Premium Ford wheels, 20 inch, for everyday driving and performance. ', 'upgrade your vehicle with these high-quality ford Set Of OEM 2022 Shelby GT 500 Wheels. Engineered for strength and style, these wheels deliver exceptional performance and a sleek look that transforms your ride. Sold as a complete set of 4 wheels - everything you need for a full installation. Size: 20 inches. Perfect for customers wanting to enhance their vehicle\'s appearance and handling. Compatible with most vehicles using standard bolt patterns. Direct fitment - no modifications required for most applications. Includes manufacturer warranty for peace of mind. Free shipping on orders over $499. Questions? Our expert team is here to help you choose the right wheels.', 1350.00,1350.00, 'SETOFOEM2022SHELBYGT', 10, 'Wheels', 'Ford', '20', '', '["/img/assets/wheel_9938_1.jpg", "/img/assets/wheel_9938_2.jpg"]', false, 'active'),
  ('Toyota 4runner & Hilux JDM 18* RALLY Turbofan Style Wheels Rims', 'toyota-4runner-hilux-jdm-18-rally-turbofan-style-wheels-rims', 'Premium Toyota wheels, 18 inch, for everyday driving and performance. ', 'upgrade your vehicle with these high-quality toyota Toyota 4runner &#038; Hilux JDM 18* RALLY Turbofan Style Wheels Rims. Engineered for strength and style, these wheels deliver exceptional performance and a sleek look that transforms your ride. Sold as a complete set of 4 wheels - everything you need for a full installation. Size: 18 inches. Perfect for customers wanting to enhance their vehicle\'s appearance and handling. Compatible with most vehicles using standard bolt patterns. Direct fitment - no modifications required for most applications. Includes manufacturer warranty for peace of mind. Free shipping on orders over $499. Questions? Our expert team is here to help you choose the right wheels.', 1000.00,1000.00, 'TOYOTA4RUNNERHILUXJD', 10, 'Wheels', 'Toyota', '18', '', '["/img/assets/wheel_9902_1.jpg"]', false, 'active'),
  ('Rays Gramlights 57dr sputter blue 5x 114.3( 4 Wheels)', 'rays-gramlights-57dr-sputter-blue-5x-114-3-4-wheels', 'Premium Rays Engineering wheels, Blue, for everyday driving and performance. ', 'upgrade your vehicle with these high-quality rays engineering Rays Gramlights 57dr sputter blue 5x 114.3( 4 Wheels). Engineered for strength and style, these wheels deliver exceptional performance and a sleek look that transforms your ride. Sold as a complete set of 4 wheels - everything you need for a full installation. Finish: Blue. Perfect for customers wanting to enhance their vehicle\'s appearance and handling. Compatible with most vehicles using standard bolt patterns. Direct fitment - no modifications required for most applications. Includes manufacturer warranty for peace of mind. Free shipping on orders over $499. Questions? Our expert team is here to help you choose the right wheels.', 1200.00,1200.00, 'RAYSGRAMLIGHTS57DRSP', 10, 'Wheels', 'Rays Engineering', '', 'Blue', '["/img/assets/wheel_9901_1.jpg", "/img/assets/wheel_9901_2.jpg"]', false, 'active');

SET FOREIGN_KEY_CHECKS = 1;